name: Snap-Receipts Deployment

on:
  push:
    branches:
      - main

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build Frontend with ENV
        working-directory: frontend
        env:
          VITE_FRONTEND_ORIGIN: ${{ secrets.VITE_FRONTEND_ORIGIN }}
        run: |
          npm install
          npm run build

      - name: Upload Frontend-Build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist/*

  backend-build:
    needs: frontend-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Download Frontend-Build
        uses: actions/download-artifact@v4
        with:
          name: 'frontend-build'
          path: 'backend/src/main/resources/static'

      - name: Build Backend mit Maven
        run: mvn -B package --file backend/pom.xml

      - name: Upload SnapReceipt.jar
        uses: actions/upload-artifact@v4
        with:
          name: 'snap-receipts'
          path: 'backend/target/snap-receipts.jar'

  push-to-docker-hub:
    needs: backend-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Backend Artefakt
        uses: actions/download-artifact@v4
        with:
          name: snap-receipts
          path: backend/target/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_IMAGE_TAG }}

  deploy-to-render:
    needs: push-to-docker-hub
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
